/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.relation_2;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Propietario
 */
public class Activity_2 extends javax.swing.JFrame {

    private JFrame frame;
    private JMenuBar toolBar;
    private JMenu options;
    private JMenuItem newPane, removePane, addText, changeToBold, centerText, exitProgram;
    private JPanel pane;
    private JLabel label;
    
    /**
     * Creates new form Activity_2
     */
    public Activity_2() {
        initComponents();
        init();
    }
    
    public void init(){
        
        frame = this;
        
        pane = new JPanel();
        
        label = new JLabel("DEFAULT");
        
        toolBar = new JMenuBar();
        
        newPane = new JMenuItem("Create Pane");
        newPane.setIcon(new ImageIcon("src/img/plus.png"));
        newPane.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.setSize(300, 100);
                pane.setBackground(Color.cyan);
                frame.add(pane);
                frame.paint(frame.getGraphics());
            }
        });
        
        removePane = new JMenuItem("Remove Pane");
        removePane.setIcon(new ImageIcon("src/img/rest.png"));
        removePane.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.remove(pane);
                frame.paint(frame.getGraphics());
            }
        });
        
        addText = new JMenuItem("Add Text"); //HAY QUE REDIMENSIONAR LA VENTANA
        addText.setIcon(new ImageIcon("src/img/plus.png"));
        addText.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.add(label);
                frame.paint(frame.getGraphics());
            }
        });
        
        changeToBold = new JMenuItem("Apply Bold to Text");
        changeToBold.setIcon(new ImageIcon("src/img/bold.png"));
        changeToBold.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                label.setFont(new Font("BOLD", Font.BOLD, 10));
                frame.paint(frame.getGraphics());
            }
        });
        
        centerText = new JMenuItem("Center Text");
        centerText.setIcon(new ImageIcon("src/img/center.png"));
        centerText.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                label.setAlignmentX(CENTER_ALIGNMENT);
                frame.paint(frame.getGraphics());
            }
        });
        
        exitProgram = new JMenuItem("Exit");
        exitProgram.setIcon(new ImageIcon("src/img/rest.png"));
        exitProgram.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(WIDTH);
            }
        });
        
        
        toolBar.add(newPane);
        toolBar.add(removePane);
        toolBar.add(addText);
        toolBar.add(changeToBold);
        toolBar.add(centerText);
        toolBar.add(exitProgram);
        
        this.setJMenuBar(toolBar);
        
        this.paint(this.getGraphics());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
