/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.relation_2;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author Propietario
 */
public class Activity_1 extends javax.swing.JFrame {

    private JFrame frame;
    private JPanel pane;
    private JMenuBar toolBar;
    private JMenu colors, insert, textFormat;
    private JMenuItem pink, purple, cyan, newPane, newSeparator, bold, red, visible;
    
    /**
     * Creates new form Activity_1
     */
    public Activity_1() {
        initComponents();
        init();
    }
    
    public void init(){
        
        frame = this;
        
        pane = new JPanel();
        pane.setSize(300, 100);
        pane.setBackground(Color.cyan);
        pane.add(new JLabel("This is my first menu"));
        
        toolBar = new JMenuBar();
        this.setJMenuBar(toolBar);
        
        //First Option
        colors = new JMenu("Colors");
        
        pink = new JMenuItem("PINK");
        pink.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.setBackground(Color.pink);
            }
        });
        
        purple = new JMenuItem("PURPLE");
        purple.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.setBackground(Color.magenta);
            }
        });
        
        cyan = new JMenuItem("CYAN");
        cyan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.setBackground(Color.cyan);
            }
        });
        
        colors.add(pink);
        colors.add(purple);
        colors.add(cyan);
        
        toolBar.add(colors);
        
        //Second Option
        insert = new JMenu("Insert");
        
        newPane = new JMenuItem("New Panel");
        newPane.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JPanel secondPane = new JPanel();
                secondPane.setSize(300, 100);
                secondPane.setLocation(0, 100);
                secondPane.setBackground(Color.red);
                
                frame.add(secondPane);
                frame.paint(frame.getGraphics());
            }
        });
        
        newSeparator = new JMenuItem("New Separator");
        newSeparator.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JSeparator separator = new JSeparator();
                separator.setSize(100, 2);
                separator.setBackground(Color.red);
                separator.setLocation(0, 100);
                
                frame.add(separator);
            }
        });
        
        insert.add(newPane);
        insert.add(newSeparator);
        
        toolBar.add(insert);
        
        //Third Option
        textFormat = new JMenu("Text Format");
        
        bold = new JMenuItem("Bold");
        bold.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.getComponent(0).setFont(new Font("bold", Font.BOLD, 12));
            }
        });
        
        red = new JMenuItem("Red");
        red.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pane.getComponent(0).setForeground(Color.red);
            }
        });
        
        visible = new JMenuItem("Visible");
        visible.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(pane.getComponent(0).isVisible()){
                    pane.getComponent(0).setVisible(false);
                }else{
                    pane.getComponent(0).setVisible(true);
                }
            }
        });
        
        textFormat.add(bold);
        textFormat.add(red);
        textFormat.add(visible);
        
        toolBar.add(textFormat);
        
        this.add(pane);
        
        this.paint(this.getGraphics());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
