/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.d.i.relacion1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author tarde
 */
public class Ejercicio_6 extends javax.swing.JFrame {

    private JButton botonAzul, botonVerde, botonRojo, botonLimpiar, botonSalir;
    private JPanel newPanel;
    private JLabel textoPanel;
    private JScrollPane scrollPane;
    private JList listPane;
    
    /**
     * Creates new form Ejercicio_1
     */
    public Ejercicio_6() {
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inicializarComponentes(){
        
        botonAzul = new JButton(); 
        
        botonAzul.setSize(90, 35);
        botonAzul.setLocation(100, 400);
        botonAzul.setText("AZUL");
        botonAzul.setBackground(Color.CYAN);
        botonAzul.setVisible(true);
        
        
        botonVerde = new JButton();
        
        botonVerde.setSize(90, 35);
        botonVerde.setLocation(200, 400);
        botonVerde.setText("VERDE");
        botonVerde.setBackground(Color.green);
        botonVerde.setVisible(true);
        
        
        botonRojo = new JButton();  
        
        botonRojo.setSize(90, 35);
        botonRojo.setLocation(300, 400);
        botonRojo.setText("ROJO");
        botonRojo.setBackground(Color.red);
        botonRojo.setVisible(true);
        
        
        botonLimpiar = new JButton();  
        
        botonLimpiar.setSize(90, 35);
        botonLimpiar.setLocation(400, 400);
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.setVisible(true);
        
        
        botonSalir = new JButton(); 
        
        botonSalir.setSize(90, 35);
        botonSalir.setLocation(500, 400);
        botonSalir.setText("SALIR");
        botonSalir.setVisible(true);
        
        
        newPanel = new JPanel();
        
        newPanel.setSize(500, 150);
        newPanel.setLocation(100, 100);
        newPanel.setBackground(Color.yellow);
        newPanel.setVisible(true);
        
        
        textoPanel = new JLabel();
        
        textoPanel.setSize(100, 50);
        textoPanel.setText("TEXTO PANEL");
        textoPanel.setBackground(Color.darkGray);
        textoPanel.setVisible(true);
        
        
        scrollPane = new JScrollPane(listPane = new JList());
        
        scrollPane.setSize(500, 150);
        scrollPane.setLocation(100, 260);
        scrollPane.setBackground(Color.orange);
        scrollPane.setVisible(true);
        scrollPane.setOpaque(true);
        
        listPane.setSize(50, 50);
        listPane.setLocation(200, 250);
        listPane.setVisible(true);
        DefaultListModel elementos = new DefaultListModel();
            
        
        this.add(botonAzul);
        this.add(botonVerde);
        this.add(botonRojo);
        this.add(botonLimpiar);
        this.add(botonSalir);
        this.add(newPanel);
        newPanel.add(textoPanel);
        this.add(scrollPane);
        
        
        //Punto 1
        ActionListener al = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                newPanel.setBackground(Color.cyan);
                elementos.addElement("Se ha pulsado el boton azul");
                listPane.setModel(elementos);
            }
        };
        
        botonAzul.addActionListener(al);
        
        //Punto 2
        ActionListener al2 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                newPanel.setBackground(Color.green);
                elementos.addElement("Se ha pulsado el boton verde");
                listPane.setModel(elementos);
            }
        };
        
        botonVerde.addActionListener(al2);
        
        //Punto 3
        ActionListener al3 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                newPanel.setBackground(Color.red);
                elementos.addElement("Se ha pulsado el boton rojo");
                listPane.setModel(elementos);
            }
        };
        
        botonRojo.addActionListener(al3);
        
        //Punto 4
        ActionListener al4 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                newPanel.setBackground(Color.yellow);
                elementos.removeAllElements();
                listPane.setModel(elementos);
            }
        };
        
        botonLimpiar.addActionListener(al4);
        
        //Punto 6
        ActionListener al5 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                elementos.addElement("Se ha pulsado el boton salir");
                listPane.setModel(elementos);
                System.exit(WIDTH);
            }
        };
        
        botonSalir.addActionListener(al5);
        
        
        this.paint(this.getGraphics());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
