/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.d.i.relacion1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.AncestorListener;

/**
 *
 * @author tarde
 */
public class Ejercicio_3 extends javax.swing.JFrame {

    private JLabel text;
    private JPanel newPanel;
    private JButton formButton;
    
    /**
     * Creates new form Ejercicio_1
     */
    public Ejercicio_3() {
        initComponents();
        inicializarComponentes();
    }
    
    
    public void inicializarComponentes(){
        
        text = new JLabel();
        newPanel = new JPanel();
        formButton = new JButton();
        
        newPanel.setSize(100, 100);
        newPanel.setLocation(100, 100);
        newPanel.setBackground(Color.pink);
        newPanel.setVisible(true);
        
        text.setText("Este es el texto de la actividad 3");
        text.setSize(300, 50);
        text.setLocation(100, 300);
        text.setVisible(true);
        
        formButton.setText("Pulsame");
        formButton.setSize(100, 100);
        formButton.setLocation(300, 100);
        formButton.setVisible(true);
        
        
        //Punto 1
        ActionListener al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               
                newPanel.setBackground(Color.blue);
            }
        };
        
        formButton.addActionListener(al);
        
        //Punto 2
        MouseListener ml = new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent me) {
                newPanel.setBackground(Color.green);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                newPanel.setBackground(Color.pink);
            }
        };
        
        newPanel.addMouseListener(ml);
        
        //Punto 3
        MouseListener ml2 = new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent me) {
                text.setOpaque(true);
                text.setBackground(Color.black);
                text.setForeground(Color.white);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                text.setOpaque(false);
                text.setForeground(Color.black);
            }
        };
        
        text.addMouseListener(ml2);
        
        //Punto 4
        MouseListener al2 = new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent me) {
                newPanel.setBackground(Color.pink);
            }

        };
        
        text.addMouseListener(al2);
        
        //Punto 5
        MouseListener ml3 = new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent me) {
                text.setForeground(Color.GREEN);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                text.setForeground(Color.black);
            }
        };
        
        formButton.addMouseListener(ml3);
        
        
        this.add(newPanel);
        this.add(text);
        this.add(formButton);
        
        this.paint(this.getGraphics());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
