/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.d.i.relacion1;

import java.awt.event.*;

/**
 *
 * @author tarde
 */
public class Ejercicio_1 extends javax.swing.JFrame {

    private javax.swing.JButton formButton1;
    private javax.swing.JButton formButton2;
    private javax.swing.JButton formButton3;
    private javax.swing.JLabel messageLabel;
    
    
    /**
     * Creates new form Ejercicio_1
     */
    public Ejercicio_1() {
        initComponents();
        inicializarComponentes();
        inicializarAcciones();
    }
    

    public void inicializarComponentes(){
    
        formButton1 = new javax.swing.JButton();
        formButton2 = new javax.swing.JButton();
        formButton3 = new javax.swing.JButton(); 
        messageLabel = new javax.swing.JLabel();
        
        formButton1.setSize(100, 50);
        formButton1.setLocation(100, 100);
        formButton1.setVisible(true);
        formButton1.setText("Boton 1");
        
        formButton2.setSize(100, 50);
        formButton2.setLocation(300, 100);
        formButton2.setVisible(true);
        formButton2.setText("Boton 2");
        
        formButton3.setSize(100, 50);
        formButton3.setLocation(500, 100);
        formButton3.setVisible(true);
        formButton3.setText("Boton 3");
        
        messageLabel.setSize(400, 100);
        messageLabel.setLocation(200, 300);
        messageLabel.setVisible(true);
        messageLabel.setText("Aun no has pulsado ningun boton");
        
        this.add(formButton1);
        this.add(formButton2);
        this.add(formButton3);
        this.add(messageLabel);
        
        this.paint(this.getGraphics());
    }
    
    
    private void inicializarAcciones(){

      formButton1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          messageLabel.setText("Has pulsado el boton 1");
          messageLabel.requestFocus(); //devuelvo foco a display para que funcione el KeyListener
        }
      });

      formButton2.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          messageLabel.setText("Has pulsado el boton 2");
          messageLabel.requestFocus();
        }
      });

      formButton3.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          messageLabel.setText("Has pulsado el boton 3");
          messageLabel.requestFocus();
      }
      });
      
      this.paint(this.getGraphics());

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
