/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.relacion_ejercicios_tema_4;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Propietario
 */
public class Ejercicio_8 extends javax.swing.JFrame {

    private GroupLayout gl;
    private JLabel texto;
    private JTextField campoTexto;
    private JCheckBox boton1, boton2, boton3, boton4;
    private JButton botonBuscar, botonCancelar;
    
    /**
     * Creates new form Ejercicio_8
     */
    public Ejercicio_8() {
        initComponents();
        ejercicio8();
    }
    
    public void ejercicio8(){
        
        texto = new JLabel("Find What:");
        
        campoTexto = new JTextField();
        
        boton1 = new JCheckBox("Match Case");
        boton2 = new JCheckBox("Wrap Around");
        boton3 = new JCheckBox("Whole Words");
        boton4 = new JCheckBox("Search Backwards");
        
        botonBuscar = new JButton("Find");
        botonCancelar = new JButton("Cancel");
        
        gl = new GroupLayout(getContentPane());
        
        gl.setAutoCreateGaps(true);
        gl.setAutoCreateContainerGaps(true);
        
        gl.setHorizontalGroup(gl.createSequentialGroup()
            .addComponent(texto)
                
            .addGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(campoTexto)
                
                .addGroup(gl.createSequentialGroup()
                    
                    .addGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(boton1)
                    .addComponent(boton2)
                    )
                        
                    .addGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(boton3)
                    .addComponent(boton4)
                    )
                )
            )
                
            .addGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(botonBuscar)
                .addComponent(botonCancelar)
            )
        );
        
        gl.linkSize(SwingConstants.HORIZONTAL, botonBuscar, botonCancelar);
        
        gl.setVerticalGroup(gl.createSequentialGroup()
            .addGroup(gl.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(texto)
                .addComponent(campoTexto)
                .addComponent(botonBuscar)
            )
                
            .addGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(gl.createSequentialGroup()
                    .addGroup(gl.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(boton1)
                        .addComponent(boton3)
                    )
                        
                    .addGroup(gl.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(boton2)
                        .addComponent(boton4)
                    )
                )
                    
                .addComponent(botonCancelar)
            )
        );
        
        this.setLayout(gl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
