/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Instalador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Usuario
 */
public class Fin extends javax.swing.JFrame {

    /**
     * Creates new form Fin
     */
    public Fin() {
        initComponents();
        
        finButton.setVisible(false);
        
        progressBar.setValue(0);
        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        titulo = new javax.swing.JLabel();
        instalarButton = new javax.swing.JButton();
        finButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        progressBar.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 103, 302, 36));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("Se va a instalar la app...");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 42, 302, 31));

        instalarButton.setText("Instalar");
        instalarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instalarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(instalarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 90, 40));

        finButton.setText("Salir");
        finButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finButtonActionPerformed(evt);
            }
        });
        getContentPane().add(finButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finButtonActionPerformed
        dispose();
    }//GEN-LAST:event_finButtonActionPerformed

    private void instalarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instalarButtonActionPerformed
        // TODO add your handling code here:
        ActionListener startProgressBar = new ActionListener() {
                    int i = 0;

                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        progressBar.setVisible(true);

                        i = i + 1;
                        progressBar.setValue(i);

                        if(progressBar.getValue() == progressBar.getMaximum()){
                            titulo.setText("Se ha instalado correctamente");
                            titulo.setVisible(true);
                            instalarButton.setVisible(false);
                            
                            finButton.setVisible(true);
                        }

                    }
                };
                
                Timer t = new Timer(75, startProgressBar);
                t.start();
    }//GEN-LAST:event_instalarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finButton;
    private javax.swing.JButton instalarButton;
    private javax.swing.JPanel panel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
