/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package D.I.ExamT2;

/**
 *
 * @author tarde
 */
public class Exercise2 extends javax.swing.JFrame {
    
    javax.swing.JTextField nameTextField;
    javax.swing.JTextField phoneTextField;
    javax.swing.JTextField dniTextField;
    
    javax.swing.JComboBox countryComboBox;
    
    javax.swing.JLabel nameLabel;
    javax.swing.JLabel phoneLabel;
    javax.swing.JLabel dniLabel;
    javax.swing.JLabel countryLabel;
    
    javax.swing.JLabel message;
        
    /**
     * Creates new form Exercise2
     */
    public Exercise2() {
        initComponents();
        
        cleanButton.setVisible(false);
        validateButton.setVisible(false);
        closeButton.setVisible(false);
        
        nameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        
        countryComboBox = new javax.swing.JComboBox();
        
        nameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cleanButton.setText("Clean");

        validateButton.setText("Validate");

        closeButton.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(validateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(cleanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanButton)
                    .addComponent(closeButton)
                    .addComponent(validateButton))
                .addGap(63, 63, 63)
                .addComponent(createButton)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        
        
        nameTextField.setVisible(true);
        nameTextField.setSize(100, 25);
        nameTextField.setLocation(100, 100);
  
        nameLabel.setVisible(true);
        nameLabel.setSize(50, 25);
        nameLabel.setText("NAME");
        nameLabel.setLocation(25, 80);
        
        phoneTextField.setVisible(true);
        phoneTextField.setSize(100, 25);
        phoneTextField.setLocation(100, 120);
        
        phoneLabel.setVisible(true);
        phoneLabel.setSize(50, 25);
        phoneLabel.setLocation(25, 120);
        phoneLabel.setText("PHONE");
        
        dniTextField.setVisible(true);
        dniTextField.setSize(100, 25);
        dniTextField.setLocation(100, 160);
        
        dniLabel.setVisible(true);
        dniLabel.setSize(50, 25);
        dniLabel.setLocation(25, 160);
        dniLabel.setText("DNI");
        
        countryComboBox.setVisible(true);
        countryComboBox.setSize(100, 25);
        countryComboBox.setLocation(25, 200);
        
        countryLabel.setVisible(true);
        countryLabel.setSize(1000, 25);
        countryLabel.setLocation(25, 300);
        countryLabel.setText("COUNTRY");
        
        cleanButton.setSize(100, 100);
        cleanButton.setLocation(25, 300);
        validateButton.setSize(100, 100);
        validateButton.setLocation(25, 300);
        closeButton.setSize(100, 100);
        closeButton.setLocation(25, 300);
        
        this.add(nameTextField);
        this.add(nameLabel);
        this.add(phoneTextField);
        this.add(phoneLabel);
        this.add(dniTextField);
        this.add(dniLabel);
        this.add(countryComboBox);
        this.add(countryLabel);
        this.paint(getGraphics());
    }//GEN-LAST:event_createButtonActionPerformed

    private void validateName(){
        
        for(int i = 0; i<nameTextField.getText().length(); i++){
            if(nameTextField.getText().length()>1 && nameTextField.getText().charAt(i)<48 && nameTextField.getText().charAt(i)>57){
                
                message = new javax.swing.JLabel();
                message.setVisible(true);
                message.setText("It is valid!");
                this.add(message);
                this.paint(getGraphics());

            }else{
                
                message = new javax.swing.JLabel();
                message.setVisible(true);
                message.setText("Only letters!");
                this.add(message);
                this.paint(getGraphics());
            }
        }
    }
    
    public void validatePhone(){
        
        for(int i = 0; i<phoneTextField.getText().length(); i++){
            if(phoneTextField.getText().length() == 9 && phoneTextField.getText().charAt(i)>=48 && phoneTextField.getText().charAt(i)<=57){
                
                message = new javax.swing.JLabel();
                message.setVisible(true);
                message.setText("It is valid!");
                this.add(message);
                this.paint(getGraphics());
                
            }else{
                
                message = new javax.swing.JLabel();
                message.setVisible(true);
                message.setText("Only nine numbers!");
                this.add(message);
                this.paint(getGraphics());
            }
        }
    }
    
    public void validateDNI(){
        
        if(dniTextField.getText().length() == 9 && dniTextField.getText().charAt(9)<48 && dniTextField.getText().charAt(9)>57){
            
            message = new javax.swing.JLabel();
            message.setVisible(true);
            message.setText("It is valid!");
            this.add(message);
            this.paint(getGraphics());
            
        }else{
            
            message = new javax.swing.JLabel();
            message.setVisible(true);
            message.setText("Only ten characters!");
            this.add(message);
            this.paint(getGraphics());
        }
    }
    
    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt){
        
        validateName();
        validatePhone();
        validateDNI();
    }
    
    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt){
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercise2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
}
